### ISSUE TITLE
Simplify seat selection interaction

### ISSUE THREAD

**Issue by danieljwait** [ICL-DRP01/frontend#2]
## User story

| | |
|---|---|
| As a | **busy student** |
| I want to | **quickly choose and leave my seat** |
| So I can | **spend as little time having to use the app as possible** |

## Tasks

- [x] User taps to choose seat upon opening the app
- [x] Big buttons to leave and take a break are then presented
- [X] All seats besides user's chosen seat are visibly disabled
