### ISSUE TITLE
Claim seats with QR code

### ISSUE THREAD

**Issue by danieljwait** [ICL-DRP01/frontend#4]
## User Story

| | |
|---|---|
| As a | **librarian seeing claimed but empty seats** |
| I want  | **make sure students can't claim a seat from outside the library** |
| So I can | **make available more seats to students** |

## Tasks
- [x] Display camera feed
- [x] Scan a QR code
- [x] Only accept QR codes of valid seat numbers
- [x] Claim the scanned seat
